title: David Romero # your name (or website title) here
logo: "/images/ProfileFotoWeb2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Analytical and forward-thinking IT professional with several yearsâ€™ experience leading digital transformation in logistics, manufacturing and finance.
  
  <br><br>
  Data Science Career Accelerator (Cambridge) | MSc in Computer Science (Warwick) | Master of Business Administration, MBA (Manchester) 
  <br><br>

  <a href="https://www.linkedin.com/in/david-romero-pina/">View my LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
